/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "night-1": "#000022",
        "night-2": "#001242",
        "night-3": "#0094C6",
        "night-4": "#005E7C",
        "night-5": "#040F16",
        "blue": {
          400: "#0094C6",
          500: "#0094C6",
          600: "#005E7C",
          900: "#001242",
        },
        "black": "#040F16",
        "primary-container": "#0094C6",
        "on-secondary": "#2f3037",
        "primary-fixed": "#d8e2ff",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-background": "#e0e2ed",
        "on-tertiary-container": "#ffffff",
        "primary-fixed-dim": "#aec6ff",
        "on-primary-fixed-variant": "#004397",
        "outline": "#8b90a0",
        "on-primary": "#002e6b",
        "on-surface-variant": "#c1c6d7",
        "secondary-fixed-dim": "#c6c6cf",
        "on-secondary-fixed-variant": "#45464e",
        "tertiary": "#c6c6c6",
        "surface-container-high": "#272a32",
        "surface-container-highest": "#32353d",
        "on-secondary-container": "#b4b4bd",
        "on-tertiary-fixed": "#1b1b1b",
        "on-surface": "#e0e2ed",
        "on-tertiary-fixed-variant": "#474747",
        "on-error": "#690005",
        "surface-container": "#1c1f27",
        "inverse-on-surface": "#2d3039",
        "secondary-fixed": "#e2e1eb",
        "surface-tint": "#aec6ff",
        "inverse-primary": "#0059c5",
        "surface-container-low": "#181b23",
        "on-secondary-fixed": "#1a1b22",
        "primary": "#aec6ff",
        "surface-variant": "#32353d",
        "tertiary-fixed": "#e2e2e2",
        "error-container": "#93000a",
        "surface-bright": "#363942",
        "outline-variant": "#414754",
        "surface-dim": "#10131b",
        "surface": "#10131b",
        "secondary": "#c6c6cf",
        "tertiary-container": "#767676",
        "secondary-container": "#45464e",
        "background": "#10131b",
        "surface-container-lowest": "#0b0e15",
        "error": "#ffb4ab",
        "on-tertiary": "#303030",
        "inverse-surface": "#e0e2ed",
        "on-primary-fixed": "#001a43",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter": "24px",
        "stack-xs": "4px",
        "unit": "8px",
        "margin-page": "64px",
        "stack-md": "16px",
        "container-max": "1280px",
        "stack-xl": "48px",
      },
      fontFamily: {
        "code-snippet": ["Space Grotesk", "sans-serif"],
        "display-lg": ["Space Grotesk", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-uppercase": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-2xl": ["Space Grotesk", "sans-serif"],
        grotesk: ["Space Grotesk", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "code-snippet": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["30px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-uppercase": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-2xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      keyframes: {
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0,148,198,0.3)' },
          '50%': { boxShadow: '0 0 20px rgba(0,148,198,0.7)' },
        },
        'scanline-scroll': {
          '0%': { backgroundPosition: '0 0' },
          '100%': { backgroundPosition: '0 100%' },
        },
        'blink': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'blink': 'blink 1s step-end infinite',
        'float': 'float 4s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
